volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}
  production_redis_data: {}
  production_iotdb_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: cosray_backend_production_django
    volumes:
      - production_django_media:/app/cosray_backend/media
    depends_on:
      - postgres
      - redis
      - iotdb
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cosray_backend_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  iotdb:
    image: apache/iotdb:2.0.5-standalone
    container_name: cosray_backend_production_iotdb
    restart: unless-stopped
    ports:
      - "6667:6667"
      - "18080:18080"
    environment:
      IOTDB_USERNAME: ${IOTDB_USERNAME:-root}
      IOTDB_PASSWORD: ${IOTDB_PASSWORD:-root}
    volumes:
      - production_iotdb_data:/iotdb/data

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: cosray_backend_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: docker.io/redis:8.2

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: cosray_backend_production_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
