volumes:
  cosray_backend_local_postgres_data: {}
  cosray_backend_local_postgres_data_backups: {}
  cosray_backend_local_iotdb_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: cosray_backend_local_django
    container_name: cosray_backend_local_django
    depends_on:
      - postgres
      - iotdb
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    environment:
      - IOTDB_HOST=iotdb
      - IOTDB_PORT=6667
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cosray_backend_production_postgres
    container_name: cosray_backend_local_postgres
    volumes:
      - cosray_backend_local_postgres_data:/var/lib/postgresql/data
      - cosray_backend_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  iotdb:
    image: apache/iotdb:2.0.5-standalone
    container_name: cosray_backend_local_iotdb
    ports:
      - "6667:6667"
      - "18080:18080"
    environment:
      - IOTDB_USERNAME=root
      - IOTDB_PASSWORD=root
    volumes:
      - cosray_backend_local_iotdb_data:/iotdb/data
