volumes:
  geocos_backend_local_postgres_data: {}
  geocos_backend_local_postgres_data_backups: {}
  geocos_backend_local_redis_data: {}
  geocos_backend_local_iotdb_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: geocos_backend_local_django
    container_name: geocos_backend_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
      - iotdb
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: geocos_backend_production_postgres
    container_name: geocos_backend_local_postgres
    volumes:
      - geocos_backend_local_postgres_data:/var/lib/postgresql/data
      - geocos_backend_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  iotdb:
    image: apache/iotdb:2.0.5-standalone
    container_name: geocos_backend_local_iotdb
    ports:
      - "6667:6667"
      - "18080:18080"
    environment:
      - IOTDB_USERNAME=root
      - IOTDB_PASSWORD=root
    volumes:
      - geocos_backend_local_iotdb_data:/iotdb/data

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: geocos_backend_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:8.2
    container_name: geocos_backend_local_redis
    volumes:
      - geocos_backend_local_redis_data:/data

  celeryworker:
    <<: *django
    image: geocos_backend_local_celeryworker
    container_name: geocos_backend_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
      - iotdb
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: geocos_backend_local_celerybeat
    container_name: geocos_backend_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
      - iotdb
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: geocos_backend_local_flower
    container_name: geocos_backend_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
